### ISSUE TITLE
Could not load file or assembly 'MathConverter, PublicKeyToken=null' or one of its dependencies.

### ISSUE THREAD

**Issue by bahriddin** [hexinnovation/MathConverter#1]
**Hello. I am new to WPF world and I couldn't use your package. Please, help with the error I am receiving (I followed all steps):**

System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Message='Provide value on 'System.Windows.StaticResourceExtension' threw an exception.' Line number '145' and line position '54'.
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at nsquared.table.apps.bitrons.MainWindow.InitializeComponent() in C:\Users\nsquared generic\Documents\nsquared-table-apps-Bitrons\nsquared.table.apps.generic\MainWindow.xaml:line 1

Inner Exception 1:
FileNotFoundException: Could not load file or assembly 'MathConverter, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

**Comment by timothylcooke** [comment]
Hi. Did you install from NuGet?

This issue is because MathConverter cannot be loaded. Typically this happens when the DLL cannot be found on disk.

Can you check the in Solution Explorer? Does anything show up there that would indicate that the file is not found?

![image](https://user-images.githubusercontent.com/8904110/34844492-ab564d64-f6df-11e7-967a-a3e29fdc5045.png)
